name: env_flavours
description: A CLI package to manage environment configurations for your projects
version: 0.1.3
repository: https://github.com/mitryp/env_flavours

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  get_it: ^8.0.0
  io: ^1.0.4
  path: ^1.9.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables: 
  env_flavours:
